export type Property = {
    id: string;
    title: string;
    type: "Departamento" | "Casa" | "Oficina" | "Terreno";
    operation: "Venta" | "Alquiler";
    city: string;
    district: string;
    address: string;
    pricePen: number;
    areaM2: number;
    beds?: number;
    baths?: number;
    parking?: number;
    featured?: boolean;
    verified?: boolean;
    imageUrl: string;
  };
  
  export const properties: Property[] = [
    {
      id: "mc-001",
      title: "Departamento moderno cerca a parques",
      type: "Departamento",
      operation: "Venta",
      city: "Lima",
      district: "Miraflores",
      address: "Cerca a Av. Larco",
      pricePen: 520000,
      areaM2: 78,
      beds: 2,
      baths: 2,
      parking: 1,
      featured: true,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1560185127-6a8c0c2a4d33?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-002",
      title: "Departamento con vista y excelente iluminación",
      type: "Departamento",
      operation: "Alquiler",
      city: "Lima",
      district: "San Isidro",
      address: "Zona empresarial",
      pricePen: 4200,
      areaM2: 92,
      beds: 2,
      baths: 2,
      parking: 1,
      featured: true,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-003",
      title: "Casa familiar con jardín y terraza",
      type: "Casa",
      operation: "Venta",
      city: "Lima",
      district: "La Molina",
      address: "Cerca a universidades",
      pricePen: 1350000,
      areaM2: 240,
      beds: 4,
      baths: 3,
      parking: 2,
      featured: true,
      verified: false,
      imageUrl:
        "https://images.unsplash.com/photo-1572120360610-d971b9d7767c?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-004",
      title: "Oficina premium lista para operar",
      type: "Oficina",
      operation: "Alquiler",
      city: "Lima",
      district: "San Isidro",
      address: "Centro financiero",
      pricePen: 6500,
      areaM2: 110,
      baths: 2,
      parking: 1,
      featured: false,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-005",
      title: "Departamento en zona céntrica, excelente conectividad",
      type: "Departamento",
      operation: "Venta",
      city: "Lima",
      district: "Surquillo",
      address: "Límite con Miraflores",
      pricePen: 398000,
      areaM2: 68,
      beds: 2,
      baths: 2,
      parking: 0,
      featured: false,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-006",
      title: "Casa amplia ideal para familia",
      type: "Casa",
      operation: "Alquiler",
      city: "Arequipa",
      district: "Yanahuara",
      address: "A pasos del mirador",
      pricePen: 4500,
      areaM2: 180,
      beds: 3,
      baths: 3,
      parking: 2,
      featured: true,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-007",
      title: "Departamento compacto para inversión",
      type: "Departamento",
      operation: "Venta",
      city: "Arequipa",
      district: "Cayma",
      address: "Zona residencial",
      pricePen: 285000,
      areaM2: 52,
      beds: 1,
      baths: 1,
      parking: 0,
      featured: false,
      verified: false,
      imageUrl:
        "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-008",
      title: "Terreno urbano con gran potencial",
      type: "Terreno",
      operation: "Venta",
      city: "Cusco",
      district: "San Sebastián",
      address: "Zona de expansión",
      pricePen: 320000,
      areaM2: 200,
      featured: false,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-009",
      title: "Departamento con balcón y vista abierta",
      type: "Departamento",
      operation: "Alquiler",
      city: "Cusco",
      district: "Wanchaq",
      address: "Cerca a avenidas principales",
      pricePen: 2200,
      areaM2: 70,
      beds: 2,
      baths: 2,
      parking: 0,
      featured: false,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-010",
      title: "Oficina moderna en edificio corporativo",
      type: "Oficina",
      operation: "Venta",
      city: "Lima",
      district: "Magdalena",
      address: "Acceso rápido a vías principales",
      pricePen: 890000,
      areaM2: 140,
      baths: 2,
      parking: 2,
      featured: false,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-011",
      title: "Casa con patio y ambiente tranquilo",
      type: "Casa",
      operation: "Venta",
      city: "Trujillo",
      district: "Víctor Larco",
      address: "Zona residencial",
      pricePen: 610000,
      areaM2: 160,
      beds: 3,
      baths: 2,
      parking: 1,
      featured: false,
      verified: false,
      imageUrl:
        "https://images.unsplash.com/photo-1605276373954-0c4a0dac5b12?auto=format&fit=crop&w=1600&q=70",
    },
    {
      id: "mc-012",
      title: "Departamento familiar con buena distribución",
      type: "Departamento",
      operation: "Venta",
      city: "Piura",
      district: "Castilla",
      address: "Cerca a comercios",
      pricePen: 250000,
      areaM2: 74,
      beds: 3,
      baths: 2,
      parking: 0,
      featured: false,
      verified: true,
      imageUrl:
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1600&q=70",
    },
  ];